# The URL the site will be built for
base_url = "https://louisponet.github.io/blog"

title = "Louis Ponet"
description = "My Blog"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

ignored_content = ["*/target/*"]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.svg"
theme = "toggle"              # light, dark, auto, toggle
comment = false
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/louisponet/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/louis-ponet-phd-384ba0b6/", icon = "linkedin" },
    { name = "scholar", url = "https://scholar.google.com/citations?hl=en&user=oAp2Siow_v8C", icon = "scholar" },
    { name = "email", url = "mailto:louisponet@gmail.com?subject=Howdy%20from%20your%20blog", icon = "email" },
]

custom_css = []

[extra.analytics]
enabled = false
