name: Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - main
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # repo checkout

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
